name: Publicar en npm

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Instalar dependencias
        run: npm install
      - name: Compilar el proyecto
        run: npm run build
      - name: Publicar en npm
        run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
