name: Publicar en npm

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.0"
      - name: Instalar dependencias
        run: npm install

  check-version:
    runs-on: ubuntu-latest
    needs: compile
    outputs:
      publish_needed: ${{ steps.check_version_result.outputs.publish_needed }}
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18s.19.0"
      - name: Obtener versión del paquete
        run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      - name: Verificar versión en npm
        id: check_version_result
        run: |
          if npm view sr-nestjs-utils@$PACKAGE_VERSION > /dev/null 2>&1; then
            echo "publish_needed=false" >> $GITHUB_ENV
          else
            echo "publish_needed=true" >> $GITHUB_ENV
          fi
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

  publish:
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.publish_needed == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.0"
          registry-url: "https://registry.npmjs.org"
      - name: Instalar dependencias
        run: npm install
      - name: Publicar en npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
